consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  DiceRollPayload:
    example:
      numDice: 1
      pattern: x0v
      roll: 3.7616058e+18
      sides: 79
    properties:
      numDice:
        description: Number of dice to roll
        example: 1
        maximum: 6
        minimum: 1
        type: integer
      pattern:
        description: Name of thingy
        example: x0v
        maxLength: 6
        minLength: 3
        pattern: ^(\d+)d(\d+)$
        type: string
      roll:
        description: The value of a roll for given pattern
        example: 3.7616058e+18
        format: int64
        type: integer
      sides:
        description: Number of sides on the dice
        example: 79
        maximum: 100
        minimum: 1
        type: integer
    required:
    - pattern
    title: DiceRollPayload
    type: object
  GoaDiceroll:
    description: Roll response message (default view)
    example:
      numDice: 2
      pattern: dva
      roll: 3.8734184e+18
      sides: 7
    properties:
      numDice:
        description: Number of dice to roll
        example: 2
        maximum: 6
        minimum: 1
        type: integer
      pattern:
        description: Name of thingy
        example: dva
        maxLength: 6
        minLength: 3
        pattern: ^(\d+)d(\d+)$
        type: string
      roll:
        description: The value of a roll for given pattern
        example: 3.8734184e+18
        format: int64
        type: integer
      sides:
        description: Number of sides on the dice
        example: 7
        maximum: 100
        minimum: 1
        type: integer
    title: 'Mediatype identifier: application/vnd.goa.diceroll; view=default'
    type: object
host: localhost:8080
info:
  description: A Chatbot for rolling dice
  title: Dice Roll Chatbot
  version: ""
paths:
  /:
    post:
      description: Roll the dice
      operationId: dice#roll
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/DiceRollPayload'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaDiceroll'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      schemes:
      - http
      summary: roll dice
      tags:
      - dice
  /{pattern}:
    get:
      description: GET landing page
      operationId: dice#index
      parameters:
      - description: Name of thingy
        in: path
        maxLength: 6
        minLength: 3
        name: pattern
        pattern: ^(\d+)d(\d+)$
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaDiceroll'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      schemes:
      - http
      summary: index dice
      tags:
      - dice
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  BadRequest:
    description: Bad Request
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/GoaDiceroll'
schemes:
- http
swagger: "2.0"
