// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=dicebot/design
// --out=$(GOPATH)/src/dicebot
// --version=v1.1.0-dirty
//
// API "dicebot": Application Controllers
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"github.com/goadesign/goa"
	"golang.org/x/net/context"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// DiceController is the controller interface for the Dice actions.
type DiceController interface {
	goa.Muxer
	Index(*IndexDiceContext) error
	Roll(*RollDiceContext) error
}

// MountDiceController "mounts" a Dice resource controller on the given service.
func MountDiceController(service *goa.Service, ctrl DiceController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewIndexDiceContext(ctx, service)
		if err != nil {
			return err
		}
		return ctrl.Index(rctx)
	}
	service.Mux.Handle("GET", "/:pattern", ctrl.MuxHandler("Index", h, nil))
	service.LogInfo("mount", "ctrl", "Dice", "action", "Index", "route", "GET /:pattern")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewRollDiceContext(ctx, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*DiceRollPayload)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Roll(rctx)
	}
	service.Mux.Handle("POST", "/", ctrl.MuxHandler("Roll", h, unmarshalRollDicePayload))
	service.LogInfo("mount", "ctrl", "Dice", "action", "Roll", "route", "POST /")
}

// unmarshalRollDicePayload unmarshals the request body into the context request data Payload field.
func unmarshalRollDicePayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &diceRollPayload{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	if err := payload.Validate(); err != nil {
		// Initialize payload with private data structure so it can be logged
		goa.ContextRequest(ctx).Payload = payload
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}
