// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=dicebot/design
// --out=$(GOPATH)/src/dicebot
// --version=v1.1.0-dirty
//
// API "dicebot": Application Media Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import "github.com/goadesign/goa"

// Roll response message (default view)
//
// Identifier: application/vnd.goa.diceroll+json; view=default
type GoaDiceroll struct {
	// Roll response text
	Text string `form:"text" json:"text" xml:"text"`
}

// Validate validates the GoaDiceroll media type instance.
func (mt *GoaDiceroll) Validate() (err error) {
	if mt.Text == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "text"))
	}
	return
}
